/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_activemq_artemis_nativo_jlibaio_LibaioContext_PooledIOCB */

#ifndef _Included_org_apache_activemq_artemis_nativo_jlibaio_LibaioContext_PooledIOCB
#define _Included_org_apache_activemq_artemis_nativo_jlibaio_LibaioContext_PooledIOCB
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
